settings:
    # General plugin settings, not much to do here...
    general:
        # Whether to blah
        stats: true
    # Regeneration settings. LOOK HERE FIRST!!!
    regen:
        # The number of times a player can regenerate.
        # Is reset to this value upon death.
        count: 12
    # DO NOT TOUCH THIS!!!
    # This is essential to the survival of your configuration settings!
    config-version: 2.5
            
    
        
    

    
